canonical/notebook-operators

charms/jupyter-controller/config.yaml
charms/jupyter-controller/reactive/jupyter_controller.py

Adds `use-istio` config option that allows manually enabling Istio integration, instead of relying on relations being made.

Allow manually enabling Istio integration

---

charms/jupyter-ui/src/charm.py

Prevents a charm from getting stuck in WaitingStatus

Set ActiveStatus by default after version checking

---

.github/workflows/integrate.yaml
README.md
bundle.yaml
charms/jupyter-ui/src/spawner_ui_config.yaml
test-requirements.txt
tests/test_charms.py

This is part of the fix for https://github.com/canonical/bundle-kubeflow/issues/423.
This change automatically selects the "Allow access to Kubeflow Pipelines" PodDefault configuration for new notebooks, provided it has been already been added to the user's namespace.  Adding the PodDefault is handled separately.
See the updated README.md file

add default access to pipelines from notebook

---

charms/jupyter-controller/metadata.yaml
charms/jupyter-ui/metadata.yaml

This PR addresses https://github.com/canonical/bundle-kubeflow/issues/425 where a PVC is created per operator, adding the `min-juju-version: 2.9.0` element to prevent that PVC creation.

Add min-juju-version element to prevent excess PVC creation

---

.gitignore
charms/jupyter-controller/config.yaml
charms/jupyter-controller/metadata.yaml
charms/jupyter-controller/src/charm.py
charms/jupyter-controller/src/prometheus_alert_rules/tempfile
charms/jupyter-controller/src/prometheus_alert_rules/unit_unavailable.rule
charms/jupyter-controller/test-requirements.txt
charms/jupyter-controller/tox.ini
charms/jupyter-ui/src/charm.py
charms/jupyter-ui/test-requirements.txt
charms/jupyter-ui/tox.ini
test-requirements.txt
tests/test_charms.py
tox.ini

Observability updates:
- rename interfaces
- use scrape charm
- hard code metrics config
- add basic alert rule
- add test
- updated bundle integration test
- the `test_notebook` test is flaky due to an [upstream bug](https://github.com/kubeflow/kubeflow/issues/6056) with jupyter-ui displaying the created notebook server status. Jupyter ui would sometimes incorrectly display the notebook server status as pending when it is created successfully with no issues.This test is now commented out. `test_create_notebook` test is added to cover the notebook creation part of `test_notebook` test.
Others:
- remove controller's test-requirements.txt as all deps needed are already listed for each env
- update other test-requirements.txt to use latest black

Update observability integration

---

charms/jupyter-controller/lib/charms/grafana_k8s/v0/grafana_dashboard.py
charms/jupyter-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
charms/jupyter-controller/metadata.yaml
charms/jupyter-controller/src/crds.yaml

Upgrades training-operator to 1.6.0-rc0 (stable version coming in the next few weeks). This PR introduces the following:
* Updates manifest files to match latest release
* Upstream notebook-controller image version bump
* Updates libraries
* WIP updates integration and unit tests
Note: These changes will be tested in k8s 1.21 in this PR and 1.22 in a different one.

jupyter-controller upgrade 1.4->1.6

---

tests/test_charms.py

Updates bundle integration tests with:
*    latest/edge istio, admission-webhook, kubeflow-profies,
kubeflow-dashboard
* Removes patch_ingressgateway (and related) as it is not needed
for istio 1.11
* Re-orders the way deps and the notebook channels are deployed
* latest/edge kubeflow-dashboard and configurations

tests: updates bundle integration tests to match notebook-operator upgrades

---

charms/jupyter-ui/metadata.yaml
charms/jupyter-ui/src/spawner_ui_config.yaml
tests/test_charms.py

Upgrades jupyter-ui to 1.6.0-rc0 (stable version coming in the next few weeks). This PR introduces the following:
* Updates manifest files to match latest release
* Upstream jupyter-web-app image version bump
* Updates libraries
Note: These changes will be tested in k8s 1.21 in this PR and 1.22 in a different one.
Merge after #40, #41

jupyter-ui upgrade 1.4->1.6

---

.github/workflows/integrate.yaml

CI change to be able to test notebook-operators in microk8s 1.22
Depends on #38, #40

ci: microk8s version bump 1.21->1.22

---

charms/jupyter-controller/metadata.yaml
charms/jupyter-ui/metadata.yaml
charms/jupyter-ui/src/spawner_ui_config.yaml

Version bump to 1.6.0 release image
NOTE: this PR depends on the latest image tag specified in [kubeflow/manifests](https://github.com/kubeflow/manifests/blob/v1.6-branch/apps/admission-webhook/upstream

chore: oci image version bump 1.6.0-rc.2 -> 1.6.0

---

.github/workflows/integrate.yaml

Pin ubuntu-20.04 as OS version for GH runners.
NOTE: lint and integration tests are expected to fail, the fixes are tracked in #69 and #68

ci: pin ubuntu version to supported 20.04

---

charms/jupyter-ui/src/logos-configmap.yaml

Fixing this issue: https://github.com/canonical/notebook-operators/issues/65

Add images per image group (python and R logo)

---

renovate.json

Summary of chnages:
- Added ignorePath to Renovate to exclude images-definitions.

fix: add ignore path to renovate

---

charms/jupyter-controller/requirements-integration.in
charms/jupyter-ui/requirements-integration.in
requirements-integration.in

Apparently the juju agent 2.9.34 is not compatible with pythonlib-juju 3.1, causing the following error:
juju.errors.JujuConnectionError: juju server-version 2.9.34 not supported To avoid this, we have to pin to a version below 3.1.

tests: pin python-libjuju<3.1 to avoid unsupported version errors

---

tools/get-images-1.7-stable.sh

Repository specific list of images.
Used by CVE scanning workflows and can be used to collect images URL for airgapped setup.
- Script that produces list of all workload managed container images that are related to this charm's workload.

feat: get all images managed by workload

---

charms/jupyter-ui/requirements-integration.in
charms/jupyter-ui/requirements-integration.txt

`juju~3` is a transitional version that is no longer supported.  We should use `juju<3` until we are using `Juju` 3.1+

fix: pin python-libjuju<3.0

---

charms/jupyter-controller/tests/integration/test_charm.py
tests/test_charms.py

This is a temporary patch until we migrate to Juju 3.1:
* Pin Prometheus revision when deploying from `latest` to avoid fetching recent patches of the charm which assume `juju >= 3.0.3`. Revision 137 was the last one seen working properly in our [CI integration tests](https://github.com/canonical/notebook-operators/actions/runs/5904696558/job/16017327250#step:4:212).
* Pin Grafana revision when deploying from `latest` to avoid fetching recent patches of the charm that fail to install on Juju 2.9. Revision 89 was the last one working properly in our CI integration tests.
Refs https://github.com/canonical/bundle-kubeflow/issues/688
Refs https://github.com/canonical/bundle-kubeflow/issues/690

fix: Pin Prometheus and Grafana revisions

---

charms/jupyter-controller/src/templates/auth_manifests.yaml.j2
charms/jupyter-ui/src/templates/auth_manifests.yaml.j2

`jupyter-controller` and `jupyter-ui` charms are sidecar charms that can create their own aggregation ClusterRoles
This moves the aggregation ClusterRoles from https://github.com/canonical/kubeflow-roles-operator/tree/main/src/manifests to its own charm.
PR in `kubeflow-roles-operator` to remove those same roles from the kubeflow-roles charm https://github.com/canonical/kubeflow-roles-operator/pull/71

feat: move aggregation ClusterRoles to charms

---

charms/jupyter-ui/src/spawner_ui_config.yaml

Jupyter Notebook ROCK images need to be integrated into `track/1.7` to provide more secure images.
- Updated spawner UI config with references to published ROCK images.
NOTE: This is cleaned up version of PR #300

feat: port jupyter notebook rocks to 1.7

---

charms/jupyter-ui/config.yaml
charms/jupyter-ui/src/charm.py
charms/jupyter-ui/src/spawner_ui_config.yaml.j2
charms/jupyter-ui/tests/integration/test_charm.py
charms/jupyter-ui/tests/unit/test_operator.py
tools/get-images.sh

part of #307 
1. Cherry-picking commits to ensure images are configurable for airgapped environment.
Only the following commits were cherry-picked:
- c559235
- eaca4e7
- 017a4ef to fix #255 in `track/1.7`
2. Update `tools/get-images.sh` to match the script in main introduced in https://github.com/canonical/notebook-operators/pull/289
```
bash tools/get-images.sh
docker.io/kubeflownotebookswg/notebook-controller:v1.7.0
docker.io/kubeflownotebookswg/jupyter-web-app:v1.7.0
kubeflownotebookswg/jupyter-scipy:v1.7.0
kubeflownotebookswg/jupyter-pytorch-full:v1.7.0
kubeflownotebookswg/jupyter-pytorch-cuda-full:v1.7.0
kubeflownotebookswg/jupyter-tensorflow-full:v1.7.0
kubeflownotebookswg/jupyter-tensorflow-cuda-full:v1.7.0
swr.cn-south-1.myhuaweicloud.com/mindspore/jupyter-mindspore:v1.6.1 …
```

make images configurable in track/1.7

---

charms/jupyter-controller/lib/charms/observability_libs/v1/kubernetes_service_patch.py
charms/jupyter-controller/src/charm.py
charms/jupyter-controller/tests/integration/test_charm.py
charms/jupyter-controller/tests/unit/test_operator.py

This commit ensures the metrics port is exposed in the Kubernetes Service for the jupyter-controller using the kubernetes_service_patch lib. This makes the metrics endpoint reachable from external prometheus scraper.
This commit also changes the unit tests slightly to adapt to the added service patcher.
Part of canonical/bundle-kubeflow#564
Please refer to the steps to reproduce in [this comment](https://github.com/canonical/bundle-kubeflow/issues/564#issuecomment-1925538870), just deploying this app. After deploying this app and cos-lite, relations and dependencies, and waiting a couple minutes (10 min) none of the alerts should fire (for this app only).

fix: expose metrics port using kubernetes_service_patch lib

---

charms/jupyter-controller/lib/charms/observability_libs/v1/kubernetes_service_patch.py
charms/jupyter-controller/src/charm.py
charms/jupyter-controller/tests/integration/test_charm.py
charms/jupyter-controller/tests/unit/test_operator.py

* fix: expose metrics port using kubernetes_service_patch lib
This commit ensures the metrics port is exposed in the Kubernetes Service for the jupyter-controller using the kubernetes_service_patch lib. This makes the metrics endpoint reachable from external prometheus scraper.
This commit also changes the unit tests slightly to adapt to the added service patcher.
Part of canonical/bundle-kubeflow#564
* tests: add an assertion for checking unit is available
The test_prometheus_grafana_integration test case was doing queries to prometheus and checking the request returned successfully and that the application name and model was listed correctly. To make this test case more accurately, we can add an assertion that also checks that the unit is available, this way we avoid issues like the one …

fix: expose metrics port using kubernetes_service_patch lib (#332)

---

charms/jupyter-controller/tests/integration/test_charm.py
tests/test_charms.py

Pins the dependency charms' versions in the integration tests to match the `track/1.7` branch
pinning istio closes #342

fix: pin charm deps in integration tests

---

charms/jupyter-controller/src/grafana_dashboards/jupyter-notebook-controller.json.tmpl
charms/jupyter-controller/tests/integration/test_charm.py

* Fix jupyter-controller's grafana dashboard by removing `uid` from the `datasource` fields.
* Add tag `ckf` to dashboard.
Part of canonical/bundle-kubeflow#856
Refs canonical/bundle-kubeflow#834

fix: Grafana dashboard shows data

---

charms/jupyter-controller/src/grafana_dashboards/jupyter-notebook-controller.json.tmpl
charms/jupyter-controller/tests/integration/test_charm.py

Backport the following:
* Remove `uid` from the `datasource` fields.
* fix typo
* Add tag `ckf` to dashboard.
* Increase retry_for_attempts to 10 attempts
* unpin prometheus
Part of canonical/bundle-kubeflow#856
Ref canonical/bundle-kubeflow#834

backport(fix): Grafana dashboard shows data from #344

---

tests/test_charms.py

This commit pins all charms that get deployed from Charmhub to a latest/edge or suggested versions. 
Part of canonical/bundle-kubeflow#863

tests: pin deployed charms to a latest and stable version

---

charms/jupyter-ui/metadata.yaml
charms/jupyter-ui/src/charm.py

canonical/kubeflow-rocks#81 introduced changes in the rockcraft project that improved readability and set a standard. This commit uses the version of the container image that corresponds to that PR.

chore: use the latest JWA image

---

charms/jupyter-ui/config.yaml
charms/jupyter-ui/requirements-integration.in
charms/jupyter-ui/requirements-integration.txt
charms/jupyter-ui/src/charm.py
charms/jupyter-ui/src/config_validators.py
charms/jupyter-ui/src/templates/spawner_ui_config.yaml.j2
charms/jupyter-ui/tests/integration/test_charm.py
charms/jupyter-ui/tests/unit/test_config_validators.py
charms/jupyter-ui/tests/unit/test_operator.py

This commit adds configuration for:
* the default number of GPUs and the GPUs available
* the default PodDefaults selected
* the Toleration configurations available
* the Affinity configurations available
These configurations are enabled through newly exposed charm configs.  These configs are lightly validated to ensure they're valid yaml, but not validated enough to ensure things like Tolerations or Affinities are proper Kubernetes yaml
Closes #336.
Code is ready to review, but I still have to flesh out the readme (that is bookkept separately in #337).  Example config inputs for testing are:
For testing, I build my environment with:
```bash
juju deploy kubeflow-dashboard --channel latest/edge --trust
juju deploy kubeflow-profiles --channel latest/edge --trust 
juju relate …
```

Enable configuration of New Notebook UI

---

charms/jupyter-ui/metadata.yaml

This commit changes the container image of the `jupyter-ui` charm to jupyter-web-app:1.8-2605035 as this latest version introduced a fix for the entrypoint command.
With the CKF bundle:
1. Deploy the CKF 1.8 bundle
2. Build the charm in this PR and refresh `jupyter-ui` with it
3. Login in the dashboard and confirm the Notebooks page is working correctly by creating a Notebook and interacting with the web app.
With relevant charms:
1. Deploy `istio-operators` from latest/edge
2. Deploy the charm in this PR
3. Relate it to `istio-pilot`
4. Wait for the charm to become active and idle
5. Look into the container logs for any anomalies.

chore: update image tag for jupyter-ui

---

charms/jupyter-controller/tests/integration/test_charm.py

This commit pins all charms that get deployed from Charmhub to a recommended latest and stable.
This commit only affects individual integration tests.
Part of https://github.com/canonical/bundle-kubeflow/issues/863

tests: pin deployed charms to latest and stable versions

---

charms/jupyter-controller/tests/integration/test_charm.py

This commit pins all charms that get deployed from Charmhub to a compatible version to the CKF 1.8 release. This commit only affects individual integration tests.
Part of canonical/bundle-kubeflow#863

tests: pin deployed charms to CKF 1.8 compatible versions

---

charms/jupyter-ui/metadata.yaml
charms/jupyter-ui/src/charm.py

canonical/kubeflow-rocks#81 introduced changes in the rockcraft project that improved readability and set a standard. This commit uses the version of the container image that corresponds to that PR.
With the CKF bundle:
1. Deploy the CKF 1.8 bundle
2. Build the charm in this PR and refresh `jupyter-ui` with it
3. Login in the dashboard and confirm the Notebooks page is working correctly by creating a Notebook and interacting with the web app.
With relevant charms:
1. Deploy `istio-operators` from 1.17/stable
2. Deploy the charm in this PR
3. Relate it to `istio-pilot`
4. Wait for the charm to become active and idle
5. Look into the container logs for any anomalies.

chore: use latest JWA image

---

charms/jupyter-ui/src/templates/spawner_ui_config.yaml.j2
charms/jupyter-ui/tests/unit/test_operator.py

Previously, the spawner_ui_config.yaml was rendered with empty strings and lists being rendered as null values in the configuration file.  For example if the GPU vendors list was empty and the default vendor was `""`,  the config file would have (shown truncated):
```
gpus:
value:
vendor: 
vendors: 
```
whereas jupyter web app expected:
```
gpus:
value:
vendor: ""
vendors: []
```
This commit updates the template to ensure we always output the correct empty values.
Closes #360

Fix spawner_ui_config.yaml to use correct null values for configurations

---

charms/jupyter-ui/config.yaml
charms/jupyter-ui/requirements-integration.in
charms/jupyter-ui/requirements-integration.txt
charms/jupyter-ui/src/charm.py
charms/jupyter-ui/src/config_validators.py
charms/jupyter-ui/src/templates/spawner_ui_config.yaml.j2
charms/jupyter-ui/tests/integration/test_charm.py
charms/jupyter-ui/tests/unit/test_config_validators.py
charms/jupyter-ui/tests/unit/test_operator.py

Backport of:
* 3ec71e9b59d3734ef43963afa8aa8402bc0155e5 from #345 
* 211a37ba040e5711e61204af802edf0c69322787 from #361 
to `track/1.8`.  See #345 for testing instructions

backport New Notebook UI configuration to 1.8

---

.github/workflows/integrate.yaml

This commit ensures the controller is bootstrapped with version 3.5.0 instead of the default as we have found issues with it.
This is a workaround for canonical/bundle-kubeflow#921.
Fixes #373

ci: bootstrap juju controller with agent version 3.5.0

---

.github/workflows/integrate.yaml

This commit ensures the controller is bootstrapped with version 3.5.0 instead of the default as we have found issues with it.
This is a workaround for canonical/bundle-kubeflow#921.
Fixes #373

ci: bootstrap juju controller with agent version 3.5.0 (#374)

---

charms/jupyter-controller/lib/charms/loki_k8s/v1/loki_push_api.py
charms/jupyter-controller/metadata.yaml
charms/jupyter-controller/requirements-integration.in
charms/jupyter-controller/requirements-integration.txt
charms/jupyter-controller/requirements-unit.txt
charms/jupyter-controller/requirements.txt
charms/jupyter-controller/src/charm.py
charms/jupyter-controller/tests/integration/test_charm.py
charms/jupyter-controller/tests/unit/test_operator.py

Added logging relation and cos integration tests from chisme.
fixes: #370
This was also manually tests with pre-deployed cos bundle.
```bash
$ juju consume u1-k8s:cos.loki-logging
$ juju integrate loki-logging grafana-agent-k8
$ charmcraft pack
$ juju deploy ./jupyter-controller_ubuntu-20.04-amd64.charm --resource oci-image=docker.io/kubeflownotebookswg/notebook-controller:v1.9.0-rc.0
$ juju integrate grafana-agent-k8s jupyter-controller:logging
```
I visit `http://<ip>/cos-grafana/explore` to explore the logs and see:

Add logging relation jupyter-controller

---

charms/jupyter-ui/lib/charms/loki_k8s/v1/loki_push_api.py
charms/jupyter-ui/metadata.yaml
charms/jupyter-ui/requirements-integration.in
charms/jupyter-ui/requirements-integration.txt
charms/jupyter-ui/requirements-unit.txt
charms/jupyter-ui/requirements.in
charms/jupyter-ui/requirements.txt
charms/jupyter-ui/src/charm.py
charms/jupyter-ui/tests/integration/test_charm.py
charms/jupyter-ui/tests/unit/test_operator.py

Added logging relation and cos integration tests from chisme.
fixes: #371
This was also manually tests with pre-deployed cos bundle.
```bash
$ juju consume u1-k8s:cos.loki-logging
$ juju integrate loki-logging grafana-agent-k8
$ juju config jupyter-ui port=5001
```
I visit `http://<ip>/cos-grafana/explore` to explore the logs and see:

Add logging relation jupyter-ui

---

charms/jupyter-controller/metadata.yaml
charms/jupyter-ui/metadata.yaml

Closes https://github.com/canonical/kubeflow-rocks/issues/99, https://github.com/canonical/kubeflow-rocks/issues/98
I have changed the images for the new rocks. Tested locally by deploying both charms, without problems.

Integrate notebook-operators rocks

---

charms/jupyter-controller/charmcraft.yaml
charms/jupyter-ui/charmcraft.yaml

Adding the rust toolchain and other dependencies to avoid issues at build time.
Part of canonical/bundle-kubeflow#989

build: add rust toolchain and other build packages

---

charms/jupyter-controller/examples/sample-notebook.yaml
charms/jupyter-controller/metadata.yaml
charms/jupyter-ui/config.yaml
charms/jupyter-ui/metadata.yaml

Closes: https://github.com/canonical/notebook-operators/issues/389
I have compared tags v1.9.0 and v1.9.0-rc.1 for this files https://github.com/kubeflow/manifests/tree/v1.9.0?tab=readme-ov-file#notebooks-10
Only the images changed

chore: update manifests for kf v1.9.0

---

charms/jupyter-ui/lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py

part of fixing https://github.com/canonical/kubeflow-dashboard-operator/issues/213
bumps the `KubeflowDashboardLinks` lib to Patch 3, lib was updated in https://github.com/canonical/kubeflow-dashboard-operator/pull/219

chore: bump dashboard links lib

---

.github/workflows/integrate.yaml
.gitignore
charms/jupyter-controller/terraform/README.md
charms/jupyter-controller/terraform/main.tf
charms/jupyter-controller/terraform/outputs.tf
charms/jupyter-controller/terraform/variables.tf
charms/jupyter-controller/terraform/versions.tf
charms/jupyter-controller/tox.ini
charms/jupyter-ui/terraform/README.md
charms/jupyter-ui/terraform/main.tf
charms/jupyter-ui/terraform/outputs.tf
charms/jupyter-ui/terraform/variables.tf
charms/jupyter-ui/terraform/versions.tf
charms/jupyter-ui/tox.ini

Create a `terraform/` directory for each of the charms that hosts their individual Terraform modules. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit) and it is based on what was done in canonical/argo-operators#198.
To test the modules:
- Clone the repository and switch this PR's branch.
- For each charm:
- `cd` into its directory 
- First run `tox -e tflint` to ensure that linting is correct
- Run `terraform apply -var "channel=latest/edge" -var "model_name=kubeflow" --auto-approve` and wait until the charm is `Active` and `Idle`.
Ref #405
Ref #404

feat: Add terraform modules for jupyter-{controller,ui}

---

.github/workflows/integrate.yaml
.gitignore
charms/jupyter-controller/terraform/README.md
charms/jupyter-controller/terraform/main.tf
charms/jupyter-controller/terraform/outputs.tf
charms/jupyter-controller/terraform/variables.tf
charms/jupyter-controller/terraform/versions.tf
charms/jupyter-controller/tox.ini
charms/jupyter-ui/terraform/README.md
charms/jupyter-ui/terraform/main.tf
charms/jupyter-ui/terraform/outputs.tf
charms/jupyter-ui/terraform/variables.tf
charms/jupyter-ui/terraform/versions.tf
charms/jupyter-ui/tox.ini

Create a `terraform/` directory for each of the charms that hosts their individual Terraform modules. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit) and it is based on what was done in https://github.com/canonical/argo-operators/pull/198.
Closes https://github.com/canonical/notebook-operators/issues/405
Closes https://github.com/canonical/notebook-operators/issues/404

feat: Backport terraform modules for jupyter-{controller,ui} from #407

---

charms/jupyter-controller/requirements-fmt.txt
charms/jupyter-controller/requirements-integration.txt
charms/jupyter-controller/requirements-lint.txt
charms/jupyter-controller/requirements-unit.txt
charms/jupyter-controller/requirements.txt
charms/jupyter-controller/tests/unit/test_operator.py
charms/jupyter-controller/tox.ini
charms/jupyter-ui/requirements-fmt.txt
charms/jupyter-ui/requirements-integration.txt
charms/jupyter-ui/requirements-lint.txt
charms/jupyter-ui/requirements-unit.txt
charms/jupyter-ui/requirements.txt
charms/jupyter-ui/tox.ini
requirements-fmt.txt
requirements-integration.in
requirements-integration.txt
requirements-lint.txt
tox.ini

* Pin pip to 24.2 due to https://github.com/jazzband/pip-tools/issues/2131
* Update python dependencies using 'tox -e update-requirements'
* Remove mocking of private ops class according to canonical/operator#1369 and canonical/seldon-core-operator#268
* Pin blinker due to seleniumbase/SeleniumBase#2782
Ref canonical/bundle-kubeflow#1177

chore: update python dependencies + pin pip, blinker

---

.github/workflows/integrate.yaml
.github/workflows/publish.yaml
charms/jupyter-controller/LICENSE
charms/jupyter-controller/charmcraft.yaml
charms/jupyter-ui/LICENSE
charms/jupyter-ui/charmcraft.yaml

Closes https://github.com/canonical/notebook-operators/issues/421
Note to reviewer: the bundle integration tests are failing due to charmcraft 3.x/edge not working correctly with parallel builds, this will be resolved once https://github.com/canonical/kfp-operators/pull/645 is merged, where charmcraftcache is being used so the issue is no longer present.
PR is pointing to the dev brach [KF-6217-use-cache-builds-dev-branch](https://github.com/canonical/notebook-operators/tree/KF-6217-use-cache-builds-dev-branch), so it is expected to be merged in red

Refactor charmcraft.yaml files to use `python` plugin and `st124` notation

---

charms/jupyter-controller/metadata.yaml
charms/jupyter-ui/config.yaml
charms/jupyter-ui/metadata.yaml

This commit updates the charms in this repository to the 1.10.0-rc.0 version, which includes:
* Using upstream's latest 1.10.0-rc.1 image for both charms
* Updating the list of images for Jupyter, Rstudio and VSCode from the dropdown menu
* Add Intel Gaudi as a new GPU vendor
See https://github.com/kubeflow/manifests/pull/3008 and https://github.com/kubeflow/manifests/pull/2995 for details on the changes. For the new GPU vendor, please note this was introduced in 1.9.1, but it was missed as CKF did not upgrade to 1.9.1.

chore: update controller and web-app to 1.10.0-rc.1

---

.github/workflows/build_and_scan_images.yaml
.github/workflows/ci.yaml
.github/workflows/promote.yaml

Closes #442 
* Updates the runners from 20.04 to 24.04
* Sets up Python3.8 before installing requirements since they are compiled with 3.8
* Removes `sg snap_microk8s` from the integration tests commands which turns out is not needed

chore: migrate GH runners to ubuntu 24.04

---

.github/workflows/ci.yaml
charms/jupyter-controller/charmcraft.yaml
charms/jupyter-controller/constraints.txt
charms/jupyter-ui/charmcraft.yaml
charms/jupyter-ui/constraints.txt

Closes https://github.com/canonical/notebook-operators/issues/456
We need to then cherry-pick this and https://github.com/canonical/notebook-operators/pull/455 to `track/1.10`

fix: install binary package for setuptools_scm

---

charms/jupyter-controller/config.yaml

Update the description of cull-idle-time from ```seconds``` to ```minutes```
- 1440min = 60min * 24h
Reference
- [Kubeflow notebook-controller](https://github.com/kubeflow/kubeflow/blob/4a26c7b5e9575410613faf7df6735aa1883a2d24/components/notebook-controller/controllers/culling_controller.go#L28)

fix: Update description of cull-idle-time from config.yaml

---

charms/jupyter-controller/requirements-integration.txt
charms/jupyter-controller/tests/integration/charms_dependencies.py
charms/jupyter-controller/tests/integration/test_charm.py

Move dependency charms deployed during tests to a separate file called
charms_dependencies.py. This enables programmatic access to them and
thus updating them centrally, probably with the use of `kfcicli`. This
uses the `CharmSpec` dataclass from chisme.
Ref canonical/bundle-kubeflow/issues/1256

refactor(tests): Move dependency charms to a separate file

---

charms/jupyter-controller/terraform/README.md
charms/jupyter-controller/terraform/main.tf
charms/jupyter-controller/terraform/variables.tf
charms/jupyter-ui/terraform/README.md
charms/jupyter-ui/terraform/main.tf
charms/jupyter-ui/terraform/variables.tf

Adds a variable to allow setting the base for `jupyter-controller` and `jupyter-ui` modules.
This variable is necessary since we've done the base migration to 24.04 in #471.
Following this PR, we should send a PR to https://github.com/canonical/charmed-kubeflow-solutions to:
1. set the base for the `jupyter-*` modules to `24.04`
2. set the channel for the `jupyter-*` modules to `1.10/edge`
The reason for this is to integrate the notebook image with the feast lib in the terraform solution, i.e. the change done in #470. This change is not yet in stable.

feat(terraform): add variable for setting the charm base

---

charms/jupyter-controller/requirements-integration.in
charms/jupyter-controller/requirements-integration.txt
charms/jupyter-controller/requirements.in
charms/jupyter-controller/requirements.txt
charms/jupyter-ui/requirements-integration.in
charms/jupyter-ui/requirements-integration.txt
charms/jupyter-ui/requirements.in
charms/jupyter-ui/requirements.txt

Bumps the chisme version to `>=0.4.11` bring the fix for https://github.com/canonical/charmed-kubeflow-chisme/issues/155
This is currently blocking the CI, see [this run](https://github.com/canonical/notebook-operators/actions/runs/15779201518/job/44481306149) for example.

fix(chore): upgrade charmed-kubeflow-chisme after upstream bugfix

---

charms/jupyter-controller/requirements-integration.in
charms/jupyter-controller/requirements-integration.txt
charms/jupyter-controller/requirements.in
charms/jupyter-controller/requirements.txt
charms/jupyter-ui/requirements-integration.in
charms/jupyter-ui/requirements-integration.txt
charms/jupyter-ui/requirements.in
charms/jupyter-ui/requirements.txt

Backports #477 
Bumps the chisme version to >=0.4.11 bring the fix for canonical/charmed-kubeflow-chisme#155.
This is currently blocking the CI, see [this run](https://github.com/canonical/notebook-operators/actions/runs/15779201518/job/44481306149) for example.

fix(chore): upgrade charmed-kubeflow-chisme after upstream bugfix (#477)

---

.github/workflows/ci.yaml
concierge.yaml

Ref: https://github.com/canonical/bundle-kubeflow/issues/1334
This PR backports the update to use Canonical K8s in our integration tests. Note that we also backport a fix to use `24.04` as base in the `release-charm` action.

(backport): Update CI to use Canonical K8s
