CODEOWNERS
=> Switch CODEOWNERS to Kubeflow team

charms/jupyter-ui/reactive/jupyter_web.py
Fixed in docker image modified from upstream. See note here for details:
https://github.com/canonical/bundle-jupyter/blob/82a57236/charms/jupyter-ui/metadata.yaml#L16
=> Remove URL rewrite

charms/jupyter-ui/src/charm.py
The service is listening at /jupyter/ internally
=> Fix jupyter-ui route handling

.github/workflows/integrate.yaml, charms/jupyter-controller/metadata.yaml, charms/jupyter-ui/config.yaml, charms/jupyter-ui/metadata.yaml, charms/jupyter-ui/src/charm.py, charms/jupyter-ui/src/spawner_ui_config.yaml, tests/test_selenium.py
Updates Jupyter UI to latest version with UI revamp based on crud-web-apps library:
https://github.com/kubeflow/kubeflow/tree/master/components/crud-web-apps/jupyter
Also includes updated and enhanced tests that require deploying more charm dependencies, but allow actually testing that a notebook properly spins up.
Fixes #10
=> Update Jupyter UI to latest version

charms/jupyter-controller/src/charm.py, charms/jupyter-controller/tests/test_operator.py
Following the standard for status handling, this PR introduces a couple of changes in the charm code to improve how unit status are managed.
=> Improves status handling for jupyter-controller

charms/jupyter-controller/src/charm.py, charms/jupyter-controller/tests/test_operator.py, charms/jupyter-ui/src/charm.py, charms/jupyter-ui/tests/test_operator.py
Following the standard for status handling, this PR introduces a couple of changes in the charm code to improve how unit status are managed.
=>  Improves status handling for jupyter-ui

.github/workflows/integrate.yaml
Remove specification on juju agent when bootstrap microk8s
=> remove bootstrap juju agent

.gitignore, charms/jupyter-ui/src/spawner_ui_config.yaml
This PRs updates the images version in `spawner_ui_config.yaml` in jupyter-ui.
=> Update jupyter notebook images to rc1

test-requirements.txt, tests/test_charms.py
Pin python-libjuju to 3.0 and update prometheus_grafana test case.
=> fixes to avoid CI issues caused by observability test cases

charms/jupyter-ui/src/spawner_ui_config.yaml, tests/test_charms.py
Add MindSpore notebook (CPU) in the notebook config list.
=> add mindspore notebook in the default notebook list

charms/jupyter-controller/metadata.yaml, charms/jupyter-controller/src/charm.py, charms/jupyter-controller/src/crds.yaml, charms/jupyter-ui/metadata.yaml, charms/jupyter-ui/src/spawner_ui_config.yaml, tests/test_charms.py
=> chore: Bump image versions

charms/jupyter-controller/lib/charms/grafana_k8s/v0/grafana_dashboard.py, charms/jupyter-controller/lib/charms/observability_libs/v0/juju_topology.py, charms/jupyter-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
bump all charm libs to most recent versions
=> chore: bump all charm libs

.github/workflows/publish.yaml, .github/workflows/release.yaml, charms/jupyter-controller/lib/charms/grafana_k8s/v0/grafana_dashboard.py, charms/jupyter-controller/lib/charms/observability_libs/v0/juju_topology.py, charms/jupyter-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py, tox.ini
This PR introduces the following changes:
* ci: pin ubuntu-20.04 for GH runners
* build: update grafana, juju topology and prometheus scrape libs
=> multiple fixes for CI: observability libs and pin ubuntu 20.04 in for runners

charms/jupyter-controller/src/charm.py, charms/jupyter-controller/test-requirements.txt, charms/jupyter-controller/tests/integration/test_charm.py, charms/jupyter-controller/tests/unit/test_operator.py, charms/jupyter-controller/tox.ini, charms/jupyter-ui/src/charm.py, charms/jupyter-ui/test-requirements.txt, charms/jupyter-ui/tests/test_operator.py, charms/jupyter-ui/tox.ini
Updates linting settings to match current standards, and fixes some code formatting.  Also pins flake8==4.0.1 due to conflicts with the flake8-copyright
=> feat: update linting settings, fix code formatting

.github/workflows/integrate.yaml, charms/jupyter-controller/metadata.yaml, charms/jupyter-ui/metadata.yaml, charms/jupyter-ui/src/spawner_ui_config.yaml
Update manifests to 1.6.1. This PR replaces #66
=> feat: update manifests to 1.6.1

.github/workflows/integrate.yaml, .github/workflows/publish.yaml, .github/workflows/release.yaml, charms/jupyter-controller/lib/charms/grafana_k8s/v0/grafana_dashboard.py, charms/jupyter-controller/lib/charms/observability_libs/v0/juju_topology.py, charms/jupyter-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py, charms/jupyter-controller/metadata.yaml, charms/jupyter-controller/requirements.txt, charms/jupyter-controller/src/charm.py, charms/jupyter-controller/test-requirements.txt, charms/jupyter-controller/tests/integration/test_charm.py, charms/jupyter-controller/tests/unit/test_operator.py, charms/jupyter-controller/tox.ini, charms/jupyter-ui/metadata.yaml, charms/jupyter-ui/src/charm.py, charms/jupyter-ui/src/spawner_ui_config.yaml, charms/jupyter-ui/test-requirements.txt, charms/jupyter-ui/tests/test_operator.py, charms/jupyter-ui/tox.ini, test-requirements.txt, tox.ini
Backport changes for version update.
=> Backport 1.6.1 changes from main to track/1.6

charms/jupyter-ui/src/charm.py, charms/jupyter-ui/src/spawner_ui_config.yaml
https://github.com/canonical/notebook-operators/issues/181
- Added update image references to UI.
=> feat: added updated images to UI

tests/test_charms.py
https://github.com/canonical/notebook-operators/issues/99
- Added trust and switched back to latest/edge.
=> fix: fixed integration tests

image-definitions/README.md, image-definitions/check-update.sh, image-definitions/check.sh, image-definitions/setup.sh, tox.ini
For more details refer to: https://github.com/canonical/notebook-operators/issues/181
- Added check for commit descrepancy between repository and the patch.
- Modified tox.ini to include image definitions maintenance.
=> Kf 941 gh181 feat container image security in tox

charms/jupyter-ui/src/spawner_ui_config.yaml
=> fix: upgrade spawner of jupyter-ui 1.7.0-rc.0->rc.1

.github/workflows/integrate.yaml
- unpin actions-operator
- remove configure kubectl done automatically by action
=> fix: Update integrate.yaml

charms/jupyter-controller/src/charm.py
https://github.com/canonical/notebook-operators/issues/239
- Added exception handling to update status handler.
=> fix: added exception handling

tools/get-images-1.7-stable.sh
Enabling checkout. Incorrect commit.
=> Kf 3784 feat get images

charms/jupyter-ui/config.yaml, charms/jupyter-ui/tests/unit/test_operator.py
=> fix: remove unavailable mindspore image

.github/workflows/integrate.yaml, charms/jupyter-controller/requirements-integration.in, charms/jupyter-controller/requirements-integration.txt, charms/jupyter-ui/requirements-integration.in, charms/jupyter-ui/requirements-integration.txt, requirements-integration.in, requirements-integration.txt
ci: update juju to 3.1 and microk8s to 1.25
=> ci: update juju to 3.1 and microk8s to 1.25

charms/jupyter-controller/examples/sample-notebook.yaml
=> fix: update example notebook to 1.8

charms/jupyter-ui/config.yaml
=> fix: correct rstudio and vscode images

tests/test_charms.py
This commit pins all charms that get deployed from Charmhub to a compatible version to the CKF 1.8 release. 
Part of https://github.com/canonical/bundle-kubeflow/issues/863
=> tests: pin deployed charms to a CKF 1.8 compatible version

charms/jupyter-controller/requirements-integration.txt, charms/jupyter-ui/requirements-integration.txt
Build charmed-kubeflow-chisme for requirements-integration.txt.
Part of canonical/charmed-kubeflow-chisme#104
=> build, tests: bump charmed-kubeflow-chisme 0.4.0 -> 0.4.1

charms/jupyter-controller/requirements-unit.txt, charms/jupyter-controller/requirements.txt, charms/jupyter-ui/requirements-unit.txt, charms/jupyter-ui/requirements.txt
Part of canonical/bundle-kubeflow#883
=> build: bump jinja2 3.1.x -> 3.1.4

charms/jupyter-controller/requirements-unit.txt, charms/jupyter-controller/requirements.txt, charms/jupyter-ui/requirements-unit.txt, charms/jupyter-ui/requirements.txt
Part of canonical/bundle-kubeflow#883
=> build: bump jinja2 3.1.x -> 3.1.4 (#394)

charms/jupyter-controller/lib/charms/grafana_k8s/v0/grafana_dashboard.py, charms/jupyter-controller/lib/charms/loki_k8s/v1/loki_push_api.py, charms/jupyter-controller/lib/charms/observability_libs/v1/kubernetes_service_patch.py, charms/jupyter-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py, charms/jupyter-controller/requirements-unit.txt, charms/jupyter-controller/requirements.txt, charms/jupyter-ui/lib/charms/loki_k8s/v1/loki_push_api.py, charms/jupyter-ui/lib/charms/observability_libs/v1/kubernetes_service_patch.py, charms/jupyter-ui/requirements-unit.txt, charms/jupyter-ui/requirements.txt
* Bump libraries using charmcraft fetch-lib.
* Check for major versions using noctua charm libraries check --major. If there is one, then commit a do-not-merge-message.txt file.
Ref canonical/bundle-kubeflow#1184
=> chore: bump libraries

charms/jupyter-ui/metadata.yaml
Closes: https://warthogs.atlassian.net/browse/KF-6969
=> chore: integrate `jupyter-web-app:1.10.0` rock

charms/jupyter-controller/metadata.yaml
closes https://warthogs.atlassian.net/browse/KF-6973
- Used the rock from https://github.com/canonical/kubeflow-rocks/actions/runs/13541373541/job/37843932170
=> chore: Update notebook controller with rc.1 rock

charms/jupyter-controller/metadata.yaml, charms/jupyter-ui/config.yaml, charms/jupyter-ui/metadata.yaml
Integrate rocks from PR https://github.com/canonical/kubeflow-rocks/pull/198
Close https://warthogs.atlassian.net/browse/KF-7143
=> chore: upgrade rocks to 1.10.0

charms/jupyter-controller/terraform/versions.tf, charms/jupyter-ui/terraform/versions.tf
Updating juju provider requirement to >=0.14.0
=> [KF-7255] Update Juju provider

charms/jupyter-ui/config.yaml
Closes: https://github.com/canonical/notebook-operators/issues/451
**For the reviewer**
Would be nice to deploy full charmed kubeflow and try to create all of these notebooks. Locally I tested jut with notebook charms.
=> feat: integrate notebook rocks

charms/jupyter-controller/terraform/variables.tf, charms/jupyter-controller/terraform/versions.tf, charms/jupyter-ui/terraform/variables.tf, charms/jupyter-ui/terraform/versions.tf
Cutting new release for branch track/1.10
=> [KF-7254] Release 1.10

charms/jupyter-controller/terraform/variables.tf, charms/jupyter-ui/terraform/variables.tf
=> [KF-7268] chore: pin channel to latest/edge

.github/workflows/ci.yaml, charms/jupyter-controller/charmcraft.yaml, charms/jupyter-controller/constraints.txt, charms/jupyter-ui/charmcraft.yaml, charms/jupyter-ui/constraints.txt
=> fix: install binary package for setuptools_scm (#460)

charms/jupyter-ui/config.yaml
Cherry pick ab71aa0 from https://github.com/canonical/notebook-operators/pull/455
=> backport(feat): integrate notebook rocks (#455)
